FROM node:16.13.0-alpine3.14

COPY . .

RUN npm install --only=prod

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

ARG PORT=80
ENV PORT $PORT
EXPOSE $PORT

ARG SOCKET_PORT=5001
ENV SOCKET_PORT $SOCKET_PORT
EXPOSE $SOCKET_PORT

CMD [ "node", "index.js" ]